// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       uint       `json:"id"`
	PostID   uint       `json:"postId"`
	Content  string     `json:"content"`
	ParentID uint       `json:"parentId"`
	Children []*Comment `json:"children"`
}

type Mutation struct {
}

type Post struct {
	ID               uint       `json:"id"`
	Title            string     `json:"title"`
	Content          string     `json:"content"`
	Comments         []*Comment `json:"comments"`
	CommentsDisabled bool       `json:"commentsDisabled"`
}

type Query struct {
}

type Subscription struct {
}
